In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv("Data1.csv")

In [4]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [6]:
df["year"].unique()

<StringArray>
['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
 '2017', '2008', '2011', '2019', '2009', '2005', '2000',  '...', '150k',
 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs', 'sale', '1995', 'ara)',
 '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry',  'Eon', 'o...',
 'ture',  'emi',  'car', 'able',  'no.', 'd...', 'SALE', 'digo', 'sell',
 'd Ex', 'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
 'cent', 'Sumo',  'cab', 't xe',  'EV2', 'r...', 'zest']
Length: 61, dtype: str

In [7]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
887    False
888    False
889    False
890    False
891    False
Length: 892, dtype: bool

In [9]:
df.duplicated().value_counts()

False    798
True      94
Name: count, dtype: int64

In [10]:
df["year"]=pd.to_numeric(df["year"], errors='coerce')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        842 non-null    float64
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: float64(1), str(5)
memory usage: 41.9 KB

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 798 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        798 non-null    str
 1   company     798 non-null    str
 2   year        749 non-null    float64
 3   Price       798 non-null    str
 4   kms_driven  748 non-null    str
 5   fuel_type   745 non-null    str
dtypes: float64(1), str(5)
memory usage: 43.6 KB

In [14]:
df.dropna(subset="year",inplace=True)

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 749 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        749 non-null    str
 1   company     749 non-null    str
 2   year        749 non-null    float64
 3   Price       749 non-null    str
 4   kms_driven  748 non-null    str
 5   fuel_type   745 non-null    str
dtypes: float64(1), str(5)
memory usage: 41.0 KB

In [16]:
df["year"]=df["year"].astype(int)

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 749 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        749 non-null    str
 1   company     749 non-null    str
 2   year        749 non-null    int64
 3   Price       749 non-null    str
 4   kms_driven  748 non-null    str
 5   fuel_type   745 non-null    str
dtypes: int64(1), str(5)
memory usage: 41.0 KB

In [18]:
df["year"].unique()

array([2007, 2006, 2018, 2014, 2015, 2012, 2013, 2016, 2010, 2017, 2008,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [19]:
df["Price"].unique()

<StringArray>
[       '80,000',      '4,25,000', 'Ask For Price',      '3,25,000',
      '5,75,000',      '1,75,000',      '1,90,000',      '8,30,000',
      '2,50,000',      '1,82,000',
 ...
        '42,000',      '1,89,000',      '1,62,000',        '35,999',
     '29,00,000',        '39,999',        '50,500',      '5,10,000',
      '8,60,000',      '5,00,001']
Length: 273, dtype: str

In [20]:
df['Price'] = df['Price'].str.replace(",","")

In [21]:
df["Price"].unique()

<StringArray>
[        '80000',        '425000', 'Ask For Price',        '325000',
        '575000',        '175000',        '190000',        '830000',
        '250000',        '182000',
 ...
         '42000',        '189000',        '162000',         '35999',
       '2900000',         '39999',         '50500',        '510000',
        '860000',        '500001']
Length: 273, dtype: str

In [22]:
df["Price"]=pd.to_numeric(df["Price"], errors='coerce')

In [23]:
df.info()

<class 'pandas.DataFrame'>
Index: 749 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        749 non-null    str
 1   company     749 non-null    str
 2   year        749 non-null    int64
 3   Price       727 non-null    float64
 4   kms_driven  748 non-null    str
 5   fuel_type   745 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 41.0 KB

In [26]:
df["Price"].unique()

array([  80000.,  425000.,      nan,  325000.,  575000.,  175000.,
        190000.,  830000.,  250000.,  182000.,  315000.,  415000.,
        320000., 1000000.,  500000.,  350000.,  160000.,  310000.,
         75000.,  100000.,  290000.,   95000.,  180000.,  385000.,
        105000.,  650000.,  689999.,  448000.,  549000.,  501000.,
        489999.,  280000.,  349999.,  284999.,  345000.,  499999.,
        235000.,  249999., 1475000.,  395000.,  220000.,  170000.,
         85000.,  200000.,  570000.,  110000.,  448999., 1891111.,
        159500.,  344999.,  449999.,  865000.,  699000.,  375000.,
        224999., 1200000.,  195000.,  351000.,  240000.,   90000.,
        155000.,  600000.,  189500.,  210000.,  390000.,  135000.,
       1600000.,  701000.,  265000.,  525000.,  372000.,  635000.,
        550000.,  485000.,  329500.,  251111.,  569999.,   69999.,
        299999.,  399999.,  450000.,  270000.,  158400.,  179000.,
        125000.,  299000.,  150000.,  275000.,  285000.,  340000.,
         70000.,  289999.,  849999.,  749999.,  274999.,  984999.,
        599999.,  244999.,  474999.,  245000.,  169500.,  370000.,
        168000.,  145000.,   98500.,  209000.,  185000.,  900000.,
        699999.,  199999.,  544999.,  199000.,  540000.,   49000.,
        700000.,   55000.,  895000.,  355000.,  565000.,  365000.,
         40000.,  400000.,  330000.,  580000.,  379000.,  219000.,
        519000.,  730000., 2000000., 2100000., 1400000.,  311000.,
        855000.,  535000.,  178000.,  300000.,  255000.,  549999.,
        380000.,   57000.,  410000.,  225000.,  120000.,   59000.,
        599000.,  675000.,   72500.,  610000.,  230000.,  520000.,
        524999.,  424999.,  644999.,  584999.,  799999.,  444999.,
        649999.,  944999.,  574999.,  374999.,  130000.,  401000.,
       1350000.,  174999.,  239999.,   99999.,  324999., 1074999.,
       1130000.,  149000.,  770000.,   30000.,  335000.,  399000.,
         65000.,  169999.,  165000.,  560000.,  950000.,  715000.,
         45000.,  940000.,  155555., 1500000.,  495000.,  800000.,
       1299000.,  530000., 1499000.,   32000.,  405000.,  760000.,
        750000.,  419000.,  140000., 1540000.,  123000.,  498000.,
        480000.,  488000., 1525000.,  548900.,  725000.,   99000.,
         52000., 2800000.,  499000.,  381000.,  278000.,  690000.,
        260000.,   90001.,  115000., 1599000.,  159000.,   51999.,
        215000.,   35000., 1150000.,  269000.,   60000.,  430000.,
       8500003.,  401919.,  490000.,  424000.,  205000.,  549900.,
        435000.,  189700.,  389700.,  360000.,  295000.,  114990.,
       1065000.,  470000.,   48000.,  188000.,  465000.,  179999.,
       2190000., 2390000., 1075000.,  475000., 1025000.,  615000.,
       1900000., 1490000., 1510000., 1850000.,  790000., 1725000.,
       1225000.,   68000.,  970000., 3100000.,  899000.,   88000.,
         53000.,  568500.,   71000.,  590000.,  795000.,   42000.,
        189000.,  162000.,   35999., 2900000.,   39999.,   50500.,
        510000.,  860000.,  500001.])

In [27]:
df.dropna(subset="Price", inplace=True)

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 727 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        727 non-null    str
 1   company     727 non-null    str
 2   year        727 non-null    int64
 3   Price       727 non-null    float64
 4   kms_driven  727 non-null    str
 5   fuel_type   724 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 39.8 KB

In [29]:
df["kms_driven"].unique()

<StringArray>
[  '45,000 kms',       '40 kms',   '28,000 kms',   '36,000 kms',
   '41,000 kms',   '25,000 kms',   '24,530 kms',   '60,000 kms',
   '30,000 kms',   '32,000 kms',
 ...
   '33,400 kms',   '60,123 kms', '1,37,495 kms',   '91,200 kms',
 '1,46,000 kms', '1,00,800 kms',    '2,100 kms',    '2,500 kms',
 '1,32,000 kms',       'Petrol']
Length: 250, dtype: str

In [30]:
df["kms_driven"]=df["kms_driven"].str.replace(",","")

In [31]:
df["kms_driven"].unique()

<StringArray>
[ '45000 kms',     '40 kms',  '28000 kms',  '36000 kms',  '41000 kms',
  '25000 kms',  '24530 kms',  '60000 kms',  '30000 kms',  '32000 kms',
 ...
  '33400 kms',  '60123 kms', '137495 kms',  '91200 kms', '146000 kms',
 '100800 kms',   '2100 kms',   '2500 kms', '132000 kms',     'Petrol']
Length: 250, dtype: str

In [32]:
df["kms_driven"]=df["kms_driven"].str.replace("kms","")

In [33]:
df["kms_driven"].unique()

<StringArray>
[ '45000 ',     '40 ',  '28000 ',  '36000 ',  '41000 ',  '25000 ',  '24530 ',
  '60000 ',  '30000 ',  '32000 ',
 ...
  '33400 ',  '60123 ', '137495 ',  '91200 ', '146000 ', '100800 ',   '2100 ',
   '2500 ', '132000 ',  'Petrol']
Length: 250, dtype: str

In [34]:
df["kms_driven"]=pd.to_numeric(df["kms_driven"], errors='coerce')

In [35]:
df["kms_driven"].unique()

array([4.50000e+04, 4.00000e+01, 2.80000e+04, 3.60000e+04, 4.10000e+04,
       2.50000e+04, 2.45300e+04, 6.00000e+04, 3.00000e+04, 3.20000e+04,
       4.86600e+04, 4.00000e+03, 1.69340e+04, 4.30000e+04, 3.55500e+04,
       3.95220e+04, 3.90000e+04, 5.50000e+04, 7.20000e+04, 1.59750e+04,
       7.00000e+04, 2.34520e+04, 3.55220e+04, 4.85080e+04, 1.54870e+04,
       8.20000e+04, 2.00000e+04, 6.80000e+04, 3.80000e+04, 2.70000e+04,
       3.30000e+04, 4.60000e+04, 1.60000e+04, 4.70000e+04, 3.50000e+04,
       3.08740e+04, 1.50000e+04, 2.96850e+04, 1.30000e+05, 1.90000e+04,
       5.40000e+04, 1.30000e+04, 3.82000e+04, 2.20000e+04, 5.00000e+04,
       1.35000e+04, 3.60000e+03, 4.58630e+04, 6.05000e+04, 1.25000e+04,
       1.80000e+04, 1.33490e+04, 2.90000e+04, 4.40000e+04, 4.20000e+04,
       1.40000e+04, 4.90000e+04, 3.62000e+04, 5.10000e+04, 1.04000e+05,
       3.33330e+04, 3.36000e+04, 5.60000e+03, 7.50000e+03, 2.60000e+04,
       2.43300e+04, 6.54800e+04, 2.00000e+05, 5.90000e+04, 9.90000e+04,
       2.80000e+03, 2.10000e+04, 1.10000e+04, 6.60000e+04, 3.00000e+03,
       7.00000e+03, 3.85000e+04, 3.72000e+04, 4.32000e+04, 2.48000e+04,
       4.58720e+04, 4.00000e+04, 1.14000e+04, 9.72000e+04, 5.20000e+04,
       3.10000e+04, 1.75430e+05, 3.70000e+04, 6.50000e+04, 3.35000e+03,
       7.50000e+04, 6.20000e+04, 7.30000e+04, 2.20000e+03, 5.48700e+04,
       3.45800e+04, 9.70000e+04, 6.00000e+01, 8.02000e+04, 3.20000e+03,
       0.00000e+00, 5.00000e+03, 5.88000e+02, 7.12000e+04, 1.75400e+05,
       9.30000e+03, 5.67580e+04, 1.00000e+04, 5.64500e+04, 5.60000e+04,
       3.27000e+04, 9.00000e+03, 7.30000e+01, 1.60000e+05, 5.85590e+04,
       5.70000e+04, 1.70000e+05, 8.00000e+04, 6.82100e+03, 2.30000e+04,
       3.40000e+04, 1.80000e+03, 4.00000e+05, 4.80000e+04, 9.00000e+04,
       1.20000e+04, 6.99000e+04, 1.66000e+05, 1.22000e+02, 3.64690e+04,
       7.80000e+03, 2.46950e+04, 1.51410e+04, 5.99100e+04, 1.00000e+05,
       4.50000e+03, 1.29000e+05, 3.00000e+02, 1.31000e+05, 1.11111e+05,
       5.94660e+04, 2.55000e+04, 4.40050e+04, 2.11000e+03, 4.32220e+04,
       1.00200e+05, 6.50000e+01, 1.40000e+05, 1.03553e+05, 5.80000e+04,
       1.20000e+05, 4.98000e+04, 1.00000e+02, 8.18760e+04, 6.02000e+03,
       5.57000e+04, 1.85000e+04, 5.30000e+04, 3.55000e+04, 2.21340e+04,
       1.00000e+03, 8.50000e+03, 8.70000e+04, 6.00000e+03, 8.00000e+03,
       5.58000e+04, 5.64000e+04, 7.21600e+04, 1.15000e+04, 1.33000e+05,
       2.00000e+03, 8.80000e+04, 6.54220e+04, 1.17000e+05, 1.50000e+05,
       1.07500e+04, 6.80000e+03, 9.80000e+03, 5.79230e+04, 3.02010e+04,
       6.20000e+03, 3.75180e+04, 2.46520e+04, 3.83000e+02, 9.50000e+04,
       3.52800e+03, 5.25000e+04, 4.79000e+04, 5.28000e+04, 1.95000e+05,
       4.80080e+04, 4.82470e+04, 9.40000e+03, 6.40000e+04, 2.13700e+03,
       1.05440e+04, 1.47000e+05, 9.00010e+04, 4.80060e+04, 7.40000e+04,
       8.50000e+04, 2.95000e+04, 3.97000e+04, 6.70000e+04, 1.93360e+04,
       6.01050e+04, 4.59330e+04, 1.02563e+05, 2.86000e+04, 4.18000e+04,
       1.16000e+05, 4.25900e+04, 7.40000e+03, 5.45000e+04, 7.60000e+04,
       1.15230e+04, 3.86000e+04, 9.55000e+04, 3.74580e+04, 8.59600e+04,
       1.25160e+04, 3.06000e+04, 2.55000e+03, 6.25000e+04, 6.90000e+04,
       2.84000e+04, 6.84850e+04, 3.50000e+03, 8.54550e+04, 6.30000e+04,
       1.60000e+03, 7.70000e+04, 2.65000e+04, 2.87500e+03, 1.39000e+04,
       1.50000e+03, 2.45000e+03, 1.62500e+03, 3.34000e+04, 6.01230e+04,
       1.37495e+05, 9.12000e+04, 1.46000e+05, 1.00800e+05, 2.10000e+03,
       2.50000e+03, 1.32000e+05,         nan])

In [36]:
df["kms_driven"]

0       45000.0
1          40.0
3       28000.0
4       36000.0
6       41000.0
         ...
886    132000.0
888     27000.0
889     40000.0
890         NaN
891         NaN
Name: kms_driven, Length: 727, dtype: float64

In [37]:
df.dropna(subset="kms_driven", inplace=True)

In [38]:
df["kms_driven"].unique()

array([4.50000e+04, 4.00000e+01, 2.80000e+04, 3.60000e+04, 4.10000e+04,
       2.50000e+04, 2.45300e+04, 6.00000e+04, 3.00000e+04, 3.20000e+04,
       4.86600e+04, 4.00000e+03, 1.69340e+04, 4.30000e+04, 3.55500e+04,
       3.95220e+04, 3.90000e+04, 5.50000e+04, 7.20000e+04, 1.59750e+04,
       7.00000e+04, 2.34520e+04, 3.55220e+04, 4.85080e+04, 1.54870e+04,
       8.20000e+04, 2.00000e+04, 6.80000e+04, 3.80000e+04, 2.70000e+04,
       3.30000e+04, 4.60000e+04, 1.60000e+04, 4.70000e+04, 3.50000e+04,
       3.08740e+04, 1.50000e+04, 2.96850e+04, 1.30000e+05, 1.90000e+04,
       5.40000e+04, 1.30000e+04, 3.82000e+04, 2.20000e+04, 5.00000e+04,
       1.35000e+04, 3.60000e+03, 4.58630e+04, 6.05000e+04, 1.25000e+04,
       1.80000e+04, 1.33490e+04, 2.90000e+04, 4.40000e+04, 4.20000e+04,
       1.40000e+04, 4.90000e+04, 3.62000e+04, 5.10000e+04, 1.04000e+05,
       3.33330e+04, 3.36000e+04, 5.60000e+03, 7.50000e+03, 2.60000e+04,
       2.43300e+04, 6.54800e+04, 2.00000e+05, 5.90000e+04, 9.90000e+04,
       2.80000e+03, 2.10000e+04, 1.10000e+04, 6.60000e+04, 3.00000e+03,
       7.00000e+03, 3.85000e+04, 3.72000e+04, 4.32000e+04, 2.48000e+04,
       4.58720e+04, 4.00000e+04, 1.14000e+04, 9.72000e+04, 5.20000e+04,
       3.10000e+04, 1.75430e+05, 3.70000e+04, 6.50000e+04, 3.35000e+03,
       7.50000e+04, 6.20000e+04, 7.30000e+04, 2.20000e+03, 5.48700e+04,
       3.45800e+04, 9.70000e+04, 6.00000e+01, 8.02000e+04, 3.20000e+03,
       0.00000e+00, 5.00000e+03, 5.88000e+02, 7.12000e+04, 1.75400e+05,
       9.30000e+03, 5.67580e+04, 1.00000e+04, 5.64500e+04, 5.60000e+04,
       3.27000e+04, 9.00000e+03, 7.30000e+01, 1.60000e+05, 5.85590e+04,
       5.70000e+04, 1.70000e+05, 8.00000e+04, 6.82100e+03, 2.30000e+04,
       3.40000e+04, 1.80000e+03, 4.00000e+05, 4.80000e+04, 9.00000e+04,
       1.20000e+04, 6.99000e+04, 1.66000e+05, 1.22000e+02, 3.64690e+04,
       7.80000e+03, 2.46950e+04, 1.51410e+04, 5.99100e+04, 1.00000e+05,
       4.50000e+03, 1.29000e+05, 3.00000e+02, 1.31000e+05, 1.11111e+05,
       5.94660e+04, 2.55000e+04, 4.40050e+04, 2.11000e+03, 4.32220e+04,
       1.00200e+05, 6.50000e+01, 1.40000e+05, 1.03553e+05, 5.80000e+04,
       1.20000e+05, 4.98000e+04, 1.00000e+02, 8.18760e+04, 6.02000e+03,
       5.57000e+04, 1.85000e+04, 5.30000e+04, 3.55000e+04, 2.21340e+04,
       1.00000e+03, 8.50000e+03, 8.70000e+04, 6.00000e+03, 8.00000e+03,
       5.58000e+04, 5.64000e+04, 7.21600e+04, 1.15000e+04, 1.33000e+05,
       2.00000e+03, 8.80000e+04, 6.54220e+04, 1.17000e+05, 1.50000e+05,
       1.07500e+04, 6.80000e+03, 9.80000e+03, 5.79230e+04, 3.02010e+04,
       6.20000e+03, 3.75180e+04, 2.46520e+04, 3.83000e+02, 9.50000e+04,
       3.52800e+03, 5.25000e+04, 4.79000e+04, 5.28000e+04, 1.95000e+05,
       4.80080e+04, 4.82470e+04, 9.40000e+03, 6.40000e+04, 2.13700e+03,
       1.05440e+04, 1.47000e+05, 9.00010e+04, 4.80060e+04, 7.40000e+04,
       8.50000e+04, 2.95000e+04, 3.97000e+04, 6.70000e+04, 1.93360e+04,
       6.01050e+04, 4.59330e+04, 1.02563e+05, 2.86000e+04, 4.18000e+04,
       1.16000e+05, 4.25900e+04, 7.40000e+03, 5.45000e+04, 7.60000e+04,
       1.15230e+04, 3.86000e+04, 9.55000e+04, 3.74580e+04, 8.59600e+04,
       1.25160e+04, 3.06000e+04, 2.55000e+03, 6.25000e+04, 6.90000e+04,
       2.84000e+04, 6.84850e+04, 3.50000e+03, 8.54550e+04, 6.30000e+04,
       1.60000e+03, 7.70000e+04, 2.65000e+04, 2.87500e+03, 1.39000e+04,
       1.50000e+03, 2.45000e+03, 1.62500e+03, 3.34000e+04, 6.01230e+04,
       1.37495e+05, 9.12000e+04, 1.46000e+05, 1.00800e+05, 2.10000e+03,
       2.50000e+03, 1.32000e+05])

In [39]:
df["kms_driven"]

0       45000.0
1          40.0
3       28000.0
4       36000.0
6       41000.0
         ...
883     50000.0
885     30000.0
886    132000.0
888     27000.0
889     40000.0
Name: kms_driven, Length: 725, dtype: float64

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 725 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        725 non-null    str
 1   company     725 non-null    str
 2   year        725 non-null    int64
 3   Price       725 non-null    float64
 4   kms_driven  725 non-null    float64
 5   fuel_type   724 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 39.6 KB

In [41]:
df["fuel_type"].unique()

<StringArray>
['Petrol', 'Diesel', nan, 'LPG']
Length: 4, dtype: str

In [42]:
df.dropna(subset="fuel_type", inplace=True)

In [43]:
df.info()

<class 'pandas.DataFrame'>
Index: 724 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        724 non-null    str
 1   company     724 non-null    str
 2   year        724 non-null    int64
 3   Price       724 non-null    float64
 4   kms_driven  724 non-null    float64
 5   fuel_type   724 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 39.6 KB

In [44]:
df["name"].unique()

<StringArray>
[  'Hyundai Santro Xing XO eRLX Euro III',
                'Mahindra Jeep CL550 MDI',
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi',
                              'Ford Figo',
                            'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
         'Maruti Suzuki Alto K10 VXi AMT',
            'Skoda Fabia Classic 1.2 MPI',
             'Maruti Suzuki Stingray VXi',
 ...
                     'Mahindra Quanto C4',
              'Maruti Suzuki Swift Dzire',
             'Hyundai i20 Select Variant',
                   'Honda City VX Petrol',
                           'Hyundai Getz',
         'Mercedes Benz C Class 200 K MT',
                            'Skoda Fabia',
             'Maruti Suzuki Ritz VXI ABS',
              'Tata Indica V2 DLE BS III',
                    'Tata Zest XM Diesel']
Length: 463, dtype: str

In [46]:
df['name'] = df.apply(lambda x: x['name'].replace(x['company'], '').strip(), axis=1)

In [47]:
df["name"].unique()

<StringArray>
[  'Santro Xing XO eRLX Euro III',                 'Jeep CL550 MDI',
 'Grand i10 Magna 1.2 Kappa VTVT',    'EcoSport Titanium 1.5L TDCi',
                           'Figo',                            'Eon',
    'EcoSport Ambiente 1.5L TDCi',        'Suzuki Alto K10 VXi AMT',
          'Fabia Classic 1.2 MPI',            'Suzuki Stingray VXi',
 ...
                      'Quanto C4',             'Suzuki Swift Dzire',
             'i20 Select Variant',                 'City VX Petrol',
                           'Getz',          'Benz C Class 200 K MT',
                          'Fabia',            'Suzuki Ritz VXI ABS',
           'Indica V2 DLE BS III',                 'Zest XM Diesel']
Length: 463, dtype: str

In [49]:
df.duplicated().value_counts()

False    724
Name: count, dtype: int64

In [50]:
df["Price"].max()

np.float64(8500003.0)

In [51]:
df=df[df["kms_driven"]>=10000]

In [52]:
df.info()

<class 'pandas.DataFrame'>
Index: 652 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        652 non-null    str
 1   company     652 non-null    str
 2   year        652 non-null    int64
 3   Price       652 non-null    float64
 4   kms_driven  652 non-null    float64
 5   fuel_type   652 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 35.7 KB

In [54]:
df[df["Price"]<=30000]

                       name company  year    Price  kms_driven fuel_type
389  Suzuki  800 Std – Befo  Maruti  1995  30000.0     55000.0    Petrol
851   Suzuki 800 Std BS III  Maruti  2000  30000.0     33400.0    Petrol

In [55]:
df = df[df['Price']<8500000]

In [56]:
df.info()

<class 'pandas.DataFrame'>
Index: 651 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        651 non-null    str
 1   company     651 non-null    str
 2   year        651 non-null    int64
 3   Price       651 non-null    float64
 4   kms_driven  651 non-null    float64
 5   fuel_type   651 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 35.6 KB

In [57]:
df.to_csv("cleaned_car_data.csv", index=False)