In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("cleaned_car_data.csv")

In [3]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000.0,Petrol
1,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000.0,Petrol
2,EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000.0,Diesel
3,Figo,Ford,2012,175000.0,41000.0,Diesel
4,Eon,Hyundai,2013,190000.0,25000.0,Petrol
...,...,...,...,...,...,...
646,Suzuki Ritz VXI ABS,Maruti,2011,270000.0,50000.0,Petrol
647,Indica V2 DLE BS III,Tata,2009,110000.0,30000.0,Diesel
648,Corolla Altis,Toyota,2009,300000.0,132000.0,Petrol
649,Zest XM Diesel,Tata,2018,260000.0,27000.0,Diesel
650,Quanto C8,Mahindra,2013,390000.0,40000.0,Diesel

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 651 entries, 0 to 650
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        651 non-null    str
 1   company     651 non-null    str
 2   year        651 non-null    int64
 3   Price       651 non-null    float64
 4   kms_driven  651 non-null    float64
 5   fuel_type   651 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 30.6 KB

In [5]:
df.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='str')

In [6]:
X=df[['name', 'company', 'year', 'kms_driven', 'fuel_type']]
X

                               name   company  year  kms_driven fuel_type
0      Santro Xing XO eRLX Euro III   Hyundai  2007     45000.0    Petrol
1    Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014     28000.0    Petrol
2       EcoSport Titanium 1.5L TDCi      Ford  2014     36000.0    Diesel
3                              Figo      Ford  2012     41000.0    Diesel
4                               Eon   Hyundai  2013     25000.0    Petrol
..                              ...       ...   ...         ...       ...
646             Suzuki Ritz VXI ABS    Maruti  2011     50000.0    Petrol
647            Indica V2 DLE BS III      Tata  2009     30000.0    Diesel
648                   Corolla Altis    Toyota  2009    132000.0    Petrol
649                  Zest XM Diesel      Tata  2018     27000.0    Diesel
650                       Quanto C8  Mahindra  2013     40000.0    Diesel

[651 rows x 5 columns]

In [7]:
y=df[["Price"]]
y

        Price
0     80000.0
1    325000.0
2    575000.0
3    175000.0
4    190000.0
..        ...
646  270000.0
647  110000.0
648  300000.0
649  260000.0
650  390000.0

[651 rows x 1 columns]

In [8]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [9]:
ohe=OneHotEncoder()

In [10]:
ohe.fit(df[["name","company", "fuel_type"]])

OneHotEncoder()

In [11]:
ohe.categories_

[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
        '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
        'A4 1.8 TFSI Multitronic Premium Plus',
        'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'Accent',
        'Accent Executive Edition', 'Accent GLE', 'Accent GLX', 'Accord',
        'Amaze', 'Amaze 1.2 S i VTEC', 'Amaze 1.5 E i DTEC',
        'Amaze 1.5 S i DTEC', 'Amaze 1.5 SX i DTEC', 'Aria Pleasure 4X2',
        'Beat', 'Beat Diesel', 'Beat LS Diesel', 'Beat LS Petrol',
        'Beat LT Diesel', 'Beat LT Opt Diesel', 'Beat LT Petrol',
        'Beat PS Diesel', 'Benz A Class A 180 Sport Petrol',
        'Benz B Class B180 Sports', 'Benz C Class 200 CDI Classic',
        'Benz C Class 200 K MT', 'Benz C Class C 220 CDI Avantgarde',
        'Benz GLA Class 200 CDI Sport', 'Bolero DI', 'Bolero DI BSII',
        'Bolero SLE BS IV', 'Bolt XM Petrol', 'Brio', 'Brio V MT',
        'Brio VX AT', 'City', 'City 1.5 E MT', 'City 1.5 EXi New',
        'City 1.5 S Inspire', 'City 1.5 S MT', 'City 1.5 V AT',
        'City 1.5 V MT', 'City 1.5 V MT Exclusive', 'City SV',
        'City VX O MT Diesel', 'City VX Petrol', 'City ZX CVT',
        'City ZX EXi', 'City ZX GXi', 'City ZX VTEC', 'Cooper S',
        'Cooper S 1.6', 'Corolla', 'Corolla Altis', 'Corolla Altis 1.8 GL',
        'Corolla Altis 1.8 J', 'Corolla Altis Diesel D4DG',
        'Corolla Altis GL Petrol', 'Corolla Altis Petrol Ltd',
        'Corolla Altis VL AT Petrol', 'Corolla H2', 'Creta',
        'Creta 1.6 SX Plus Petrol', 'Cruze LTZ', 'Cruze LTZ AT', 'Duster',
        'Duster 110 PS RxL Diesel', 'Duster 110 PS RxZ Diesel',
        'Duster 110 PS RxZ Diesel Plus', 'Duster 110PS Diesel RxZ',
        'Duster 85 PS RxE Diesel', 'Duster 85 PS RxL Diesel',
        'Duster 85 PS RxL Explore LE',
        'Duster 85PS Diesel RxL Optional with Nav', 'Duster RxL Petrol',
        'EcoSport', 'EcoSport Ambiente 1.5L TDCi',
        'EcoSport Titanium 1.5 TDCi', 'EcoSport Titanium 1.5L TDCi',
        'EcoSport Trend 1.5 Ti VCT', 'EcoSport Trend 1.5L TDCi',
        'EcoSport Trend 1.5L Ti VCT', 'Elantra 1.8 S', 'Elantra SX',
        'Elite i20', 'Elite i20 Asta 1.2', 'Elite i20 Asta 1.4 CRDI',
        'Elite i20 Magna 1.2', 'Elite i20 Sportz 1.2', 'Enjoy',
        'Enjoy 1.4 LS 8 STR', 'Eon', 'Eon D Lite Plus', 'Eon Era Plus',
        'Eon Magna Plus', 'Eon Sportz', 'Etios', 'Etios G', 'Etios GD',
        'Etios Liva', 'Etios Liva Diesel', 'Etios Liva G', 'Etios Liva GD',
        'Fabia', 'Fabia 1.2L Diesel Ambiente',
        'Fabia 1.2L Diesel Elegance', 'Fabia Classic 1.2 MPI', 'Fiesta',
        'Fiesta SXi 1.6 ABS', 'Figo', 'Figo Diesel EXI',
        'Figo Diesel EXI Option', 'Figo Duratorq Diesel Titanium 1.4',
        'Figo Petrol LXI', 'Fluidic Verna 1.6 CRDi SX', 'Fortuner',
        'Fortuner 3.0 4x2 MT', 'Fortuner 3.0 4x4 MT',
        'Fusion 1.4 TDCi Diesel', 'Getz', 'Getz GLE', 'Getz Prime 1.3 GLX',
        'Getz Prime 1.3 GVS', 'Go Plus', 'Grand i10 Asta 1.1 CRDi',
        'Grand i10 Asta 1.2 Kappa VTVT', 'Grand i10 Asta 1.2 Kappa VTVT O',
        'Grand i10 Magna 1.2 Kappa VTVT',
        'Grand i10 Magna AT 1.2 Kappa VTVT',
        'Grand i10 Sportz 1.2 Kappa VTVT',
        'Grand i10 Sportz O 1.2 Kappa VTVT', 'Ikon 1.3 CLXi NXt Finesse',
        'Ikon 1.3 Flair Josh 100', 'Ikon 1.6 Nxt', 'Indica', 'Indica V2',
        'Indica V2 DLE BS III', 'Indica V2 DLG', 'Indica V2 DLS BS III',
        'Indica V2 DLX BS III', 'Indica V2 LS', 'Indica V2 Xeta e GLE',
        'Indica V2 eLS', 'Indica eV2 LS', 'Indica eV2 eXeta eGLX',
        'Indigo CS', 'Indigo CS GLS', 'Indigo CS LS DiCOR',
        'Indigo CS eLS BS IV', 'Indigo CS eLX BS IV', 'Indigo LS',
        'Indigo LX TDI BS III', 'Indigo Marina LS', 'Indigo eCS',
        'Indigo eCS LS CR4 BS IV', 'Indigo eCS LX CR4 BS IV',
        'Indigo eCS LX TDI BS III', 'Indigo eCS VX CR4 BS IV',
        'Innova 2.0 G 8 STR BS IV', 'Innova 2.0 G4', 'Innova 2.5 E 8 STR',
        'Innova 2.5 G BS III 8 STR', 'Innova 2.5 GX BS IV 7 STR',
        'Innova 2.5 V 7 STR', 'Innova 2.5 Z Diesel 7 Seater', 'Jazz S MT',
        'Jazz VX MT', 'Jetta Comfortline 1.9 TDI AT',
        'Jetta Highline TDI AT', 'KUV100', 'KUV100 K8 D 6 STR', 'Kwid',
        'Kwid 1.0 RXT AMT', 'Kwid RXT', 'Kwid RXT Opt', 'Lancer 1.8 LXi',
        'Laura', 'Linea Emotion 1.4 L T Jet Petrol', 'Lodgy 85 PS RXL',
        'Logan', 'Logan Diesel 1.5 DLS', 'Manza', 'Manza Aqua Quadrajet',
        'Manza Aura Quadrajet', 'Manza ELAN Quadrajet', 'Micra XL',
        'Micra XV', 'Mobilio', 'Mobilio S i DTEC', 'Motors Ambassador',
        'Motors Ambassador Classic Mark 4 – Befo', 'Motors One SUV',
        'Nano GenX XMA', 'Nano LX Special Edition',
        'Octavia Classic 1.9 TDI MT', 'Pajero Sport 2.5 AT',
        'Pajero Sport Limited Edition', 'Passat Diesel Comfortline AT',
        'Petra ELX 1.2 PS', 'Polo', 'Polo Highline Exquisite P',
        'Polo Highline1.2L P', 'Polo Trendline 1.5L D',
        'Punto Emotion 1.2', 'Q3 2.0 TDI quattro Premium',
        'Q5 2.0 TDI quattro Premium Plus', 'Q7', 'Qualis', 'Quanto C4',
        'Quanto C8', 'Rapid Elegance 1.6 TDI CR MT', 'Redi GO',
        'Redi GO S', 'Rover Freelander 2 SE', 'S80 Summum D4',
        'Sail 1.2 LS', 'Sail UVA Petrol LT ABS', 'Santro',
        'Santro AE GLS Audio', 'Santro Xing', 'Santro Xing GL',
        'Santro Xing GLS', 'Santro Xing XL AT eRLX Euro III',
        'Santro Xing XL eRLX Euro III', 'Santro Xing XO eRLX Euro III',
        'Scala RxL Diesel', 'Scala RxL Diesel Travelogue', 'Scorpio',
        'Scorpio 2.6 CRDe', 'Scorpio 2.6 SLX', 'Scorpio LX BS III',
        'Scorpio S10', 'Scorpio S10 4WD', 'Scorpio S4',
        'Scorpio SLE BS IV', 'Scorpio SLX', 'Scorpio SLX 2.6 Turbo 8 Str',
        'Scorpio VLX 2.2 mHawk Airbag BSIV', 'Scorpio VLX 2WD BS IV',
        'Scorpio VLX 4WD Airbag', 'Scorpio VLX Airbag',
        'Scorpio VLX Special Edition BS III', 'Scorpio Vlx BSIV',
        'Scorpio W Turbo 2.6DX 9 Seater', 'Sonata Transform 2.4 GDi MT',
        'Spark', 'Spark 1.0 LT', 'Spark LS 1.0', 'Spark LT 1.0',
        'Spark LT 1.0 Airbag', 'Sumo Gold EX BS IV', 'Sumo Gold FX BSIII',
        'Sumo Gold LX BS IV', 'Sumo Gold Select Variant',
        'Sumo Grande MKII GX', 'Sumo Victa EX 10 by 7 Str BSIII', 'Sunny',
        'Sunny XL', 'Superb 1.8 TFSI AT', 'Suzuki  800 AC',
        'Suzuki  800 Std', 'Suzuki  800 Std – Befo', 'Suzuki 800',
        'Suzuki 800 Std BS III', 'Suzuki A Star Lxi', 'Suzuki Alto',
        'Suzuki Alto 800', 'Suzuki Alto 800 LXI CNG O',
        'Suzuki Alto 800 Lx', 'Suzuki Alto 800 Lxi', 'Suzuki Alto 800 Vxi',
        'Suzuki Alto K10 LXi CNG', 'Suzuki Alto K10 VXi',
        'Suzuki Alto K10 VXi AMT', 'Suzuki Alto K10 VXi AT',
        'Suzuki Alto LX', 'Suzuki Alto LXi BS III',
        'Suzuki Alto Std BS IV', 'Suzuki Baleno Delta 1.2',
        'Suzuki Baleno Sigma 1.2', 'Suzuki Celerio VDi',
        'Suzuki Ciaz ZXI Plus', 'Suzuki Ciaz ZXi Plus RS', 'Suzuki Dzire',
        'Suzuki Dzire LDI', 'Suzuki Dzire VDI', 'Suzuki Dzire ZXI',
        'Suzuki Eeco 5 STR WITH AC HTR', 'Suzuki Eeco 7 STR',
        'Suzuki Ertiga', 'Suzuki Ertiga LDi', 'Suzuki Ertiga VDi',
        'Suzuki Ertiga Vxi', 'Suzuki Ertiga ZXI Plus', 'Suzuki Ertiga ZXi',
        'Suzuki Esteem LXi BS III', 'Suzuki Esteem VXi BS III',
        'Suzuki Estilo LX BS IV', 'Suzuki Estilo VXi ABS BS IV',
        'Suzuki Omni', 'Suzuki Omni 8 STR BS III',
        'Suzuki Omni E 8 STR BS IV', 'Suzuki Omni LPG BS IV',
        'Suzuki Omni Limited Edition', 'Suzuki Ritz',
        'Suzuki Ritz GENUS VXI', 'Suzuki Ritz LDi', 'Suzuki Ritz VDi',
        'Suzuki Ritz VXI', 'Suzuki Ritz VXI ABS',
        'Suzuki S Cross Sigma 1.3', 'Suzuki SX4',
        'Suzuki SX4 Celebration Diesel', 'Suzuki SX4 ZXI MT',
        'Suzuki Stingray VXi', 'Suzuki Swift', 'Suzuki Swift Dzire',
        'Suzuki Swift Dzire Tour LDi', 'Suzuki Swift Dzire Tour LXi',
        'Suzuki Swift Dzire Tour VDi', 'Suzuki Swift Dzire VDi',
        'Suzuki Swift Dzire VXi 1.2 BS IV', 'Suzuki Swift Dzire ZDi',
        'Suzuki Swift GLAM', 'Suzuki Swift LDi', 'Suzuki Swift RS VDI',
        'Suzuki Swift Select Variant', 'Suzuki Swift VDi',
        'Suzuki Swift VDi ABS', 'Suzuki Swift VDi BS IV',
        'Suzuki Swift VXI BSIII', 'Suzuki Swift VXi 1.2 ABS BS IV',
        'Suzuki Swift VXi 1.2 BS IV', 'Suzuki Swift Vdi BSIII',
        'Suzuki Swift ZXi 1.2 BS IV', 'Suzuki Versa DX2 8 SEATER BSIII',
        'Suzuki Vitara Brezza', 'Suzuki Vitara Brezza LDi O',
        'Suzuki Vitara Brezza ZDi', 'Suzuki Wagon R', 'Suzuki Wagon R 1.0',
        'Suzuki Wagon R 1.0 VXi', 'Suzuki Wagon R AX BSIV',
        'Suzuki Wagon R Duo Lxi', 'Suzuki Wagon R LX BS III',
        'Suzuki Wagon R LX BS IV', 'Suzuki Wagon R LXI BS IV',
        'Suzuki Wagon R LXi BS III', 'Suzuki Wagon R Select Variant',
        'Suzuki Wagon R VXI BS IV', 'Suzuki Wagon R VXi BS III',
        'Suzuki Wagon R VXi Minor', 'Suzuki Zen Estilo',
        'Suzuki Zen Estilo LXI Green CNG', 'Suzuki Zen LX BSII',
        'Suzuki Zen LXi BS III', 'Suzuki Zen LXi BSII', 'Suzuki Zen VX',
        'TUV300 T4 Plus', 'Tavera LS B3 10 Seats BSII', 'Tavera Neo',
        'Terrano XL D Plus', 'Thar CRDe 4x4 AC', 'Tiago Revotron XZ',
        'Vento Comfortline Diesel', 'Vento Comfortline Petrol',
        'Vento Highline Plus 1.5 Diesel AT',
        'Vento Konekt Diesel Highline', 'Venture EX 8 STR', 'Verna',
        'Verna 1.4 VTVT', 'Verna 1.6 CRDI E', 'Verna 1.6 CRDI SX',
        'Verna 1.6 CRDI SX Plus AT', 'Verna 1.6 EX VTVT', 'Verna Fluidic',
        'Verna Fluidic 1.6 VTVT SX', 'Verna Fluidic New',
        'Verna Transform SX VTVT', 'Verna VGT CRDi SX ABS',
        'Vista Quadrajet VX', 'WR V S MT Petrol', 'X1', 'X1 sDrive20d',
        'X1 xDrive20d xLine', 'XF 2.2 Diesel Luxury', 'XUV500',
        'XUV500 W10', 'XUV500 W6', 'XUV500 W8', 'XUV500 W8 AWD 2013',
        'Xcent Base 1.1 CRDi', 'Xcent SX 1.2', 'Xylo D2', 'Xylo D2 BS IV',
        'Xylo E4', 'Xylo E8', 'Xylo E8 BS IV',
        'Yeti Ambition 2.0 TDI CR 4x2', 'Zest Quadrajet 1.3',
        'Zest XE 75 PS Diesel', 'Zest XM Diesel', 'i10', 'i10 Era',
        'i10 Magna 1.2', 'i10 Magna 1.2 Kappa2', 'i10 Sportz',
        'i10 Sportz 1.2', 'i20', 'i20 Active', 'i20 Active 1.2 SX',
        'i20 Active 1.4L SX O', 'i20 Asta', 'i20 Asta 1.2',
        'i20 Asta 1.4 CRDI 6 Speed', 'i20 Magna', 'i20 Magna 1.2',
        'i20 Magna O 1.2', 'i20 Select Variant', 'i20 Sportz 1.2',
        'i20 Sportz 1.4 CRDI'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Land', 'Mahindra',
        'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan', 'Renault',
        'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'], dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [12]:
ct = make_column_transformer((OneHotEncoder(categories=ohe.categories_),["name","company","fuel_type"]),remainder="passthrough")

In [13]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
       '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'Accent',
       'Accent Executive Edition', 'Accent GLE', 'Accent GLX', 'Acc...
       'i20 Sportz 1.4 CRDI'], dtype=object),
                                                           array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Land', 'Mahindra',
       'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan', 'Renault',
       'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'], dtype=object),
                                                           array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                 ['name', 'company', 'fuel_type'])])

In [14]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [15]:
from sklearn.pipeline import make_pipeline

In [16]:
pipe = make_pipeline(ct,reg)

In [17]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
       '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'Accent',
       'Accent Executive...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Land', 'Mahindra',
       'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan', 'Renault',
       'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'], dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.1,random_state=0)

In [20]:
X_train

                                  name   company  year  kms_driven fuel_type
76          Suzuki Swift VXi 1.2 BS IV    Maruti  2013     13349.0    Petrol
246                         i20 Active   Hyundai  2015     35000.0    Diesel
504           Suzuki Omni 8 STR BS III    Maruti  2009     45000.0    Petrol
514  Benz C Class C 220 CDI Avantgarde  Mercedes  2009     76000.0    Diesel
428                     Eon Magna Plus   Hyundai  2013     23000.0    Petrol
..                                 ...       ...   ...         ...       ...
9                  Elite i20 Magna 1.2   Hyundai  2014     32000.0    Petrol
359                      City 1.5 S MT     Honda  2014     22000.0    Petrol
192                  Terrano XL D Plus    Nissan  2015     60000.0    Diesel
629                             Qualis    Toyota  2003    100000.0    Diesel
559                  Suzuki Ertiga VDi    Maruti  2012     48000.0    Diesel

[585 rows x 5 columns]

In [21]:
y_train

         Price
76    372000.0
246   574999.0
504    85000.0
514  1225000.0
428   185000.0
..         ...
9     415000.0
359   499000.0
192   499999.0
629   180000.0
559   500000.0

[585 rows x 1 columns]

In [22]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
       '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'Accent',
       'Accent Executive...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Land', 'Mahindra',
       'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan', 'Renault',
       'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'], dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [23]:
input = pd.DataFrame(data=[["Santro Xing XO eRLX Euro III","Hyundai",2020,45000.0,"Petrol"]],columns=['name', 'company', 'year', 'kms_driven', 'fuel_type'])
input

                           name  company  year  kms_driven fuel_type
0  Santro Xing XO eRLX Euro III  Hyundai  2020     45000.0    Petrol

In [24]:
pipe.predict(input)

array([[477516.12050456]])

In [28]:
import pickle as pkl

In [29]:
pkl.dump(pipe,open("CPP.pkl","wb+"))