In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("Data1.csv")
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [4]:
df["kms_driven"].isnull().value_counts()

kms_driven
False    840
True      52
Name: count, dtype: int64

In [5]:
df.dropna(subset=["kms_driven"],inplace=True)

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 840 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        840 non-null    str
 1   company     840 non-null    str
 2   year        840 non-null    str
 3   Price       840 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 45.9 KB

In [7]:
df.dropna(subset=["fuel_type"],inplace=True)

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 837 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        837 non-null    str
 1   company     837 non-null    str
 2   year        837 non-null    str
 3   Price       837 non-null    str
 4   kms_driven  837 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 45.8 KB

In [9]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,"2,70,000","50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

In [10]:
df['year'] = pd.to_numeric(df['year'], errors='coerce')

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 837 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        837 non-null    str
 1   company     837 non-null    str
 2   year        837 non-null    int64
 3   Price       837 non-null    str
 4   kms_driven  837 non-null    str
 5   fuel_type   837 non-null    str
dtypes: int64(1), str(5)
memory usage: 45.8 KB

In [12]:
df["year"].unique()

array([2007, 2006, 2018, 2014, 2015, 2012, 2013, 2016, 2010, 2017, 2008,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [13]:
df["Price"].unique()

<StringArray>
[       '80,000',      '4,25,000', 'Ask For Price',      '3,25,000',
      '5,75,000',      '1,75,000',      '1,90,000',      '8,30,000',
      '2,50,000',      '1,82,000',
 ...
        '42,000',      '1,89,000',      '1,62,000',        '35,999',
     '29,00,000',        '39,999',        '50,500',      '5,10,000',
      '8,60,000',      '5,00,001']
Length: 273, dtype: str

In [14]:
df['Price'] = df['Price'].str.replace(',', '')

In [15]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,"45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,"28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,"36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,"50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,"30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,"1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,"27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,"40,000 kms",Diesel

In [16]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

In [17]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,"45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,NaN,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,"28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,"36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000.0,"50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000.0,"30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,300000.0,"1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,260000.0,"27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000.0,"40,000 kms",Diesel

In [18]:
df["Price"].unique()

array([  80000.,  425000.,      nan,  325000.,  575000.,  175000.,
        190000.,  830000.,  250000.,  182000.,  315000.,  415000.,
        320000., 1000000.,  500000.,  350000.,  160000.,  310000.,
         75000.,  100000.,  290000.,   95000.,  180000.,  385000.,
        105000.,  650000.,  689999.,  448000.,  549000.,  501000.,
        489999.,  280000.,  349999.,  284999.,  345000.,  499999.,
        235000.,  249999., 1475000.,  395000.,  220000.,  170000.,
         85000.,  200000.,  570000.,  110000.,  448999., 1891111.,
        159500.,  344999.,  449999.,  865000.,  699000.,  375000.,
        224999., 1200000.,  195000.,  351000.,  240000.,   90000.,
        155000.,  600000.,  189500.,  210000.,  390000.,  135000.,
       1600000.,  701000.,  265000.,  525000.,  372000.,  635000.,
        550000.,  485000.,  329500.,  251111.,  569999.,   69999.,
        299999.,  399999.,  450000.,  270000.,  158400.,  179000.,
        125000.,  299000.,  150000.,  285000.,  340000.,   70000.,
        289999.,  849999.,  749999.,  274999.,  984999.,  599999.,
        244999.,  474999.,  245000.,  169500.,  275000.,  370000.,
        168000.,  145000.,   98500.,  209000.,  185000.,  900000.,
        699999.,  199999.,  544999.,  199000.,  540000.,   49000.,
        700000.,   55000.,  895000.,  355000.,  565000.,  365000.,
         40000.,  400000.,  330000.,  580000.,  379000.,  219000.,
        519000.,  730000., 2000000., 2100000., 1400000.,  311000.,
        855000.,  535000.,  178000.,  300000.,  255000.,  549999.,
        380000.,   57000.,  410000.,  225000.,  120000.,   59000.,
        599000.,  675000.,   72500.,  610000.,  230000.,  520000.,
        524999.,  424999.,  644999.,  584999.,  799999.,  444999.,
        649999.,  944999.,  574999.,  374999.,  130000.,  401000.,
       1350000.,  174999.,  239999.,   99999.,  324999., 1074999.,
       1130000.,  149000.,  770000.,   30000.,  335000.,  399000.,
         65000.,  169999.,  165000.,  560000.,  950000.,  715000.,
         45000.,  940000.,  155555., 1500000.,  495000.,  800000.,
       1299000.,  530000., 1499000.,   32000.,  405000.,  760000.,
        750000.,  419000.,  140000., 1540000.,  123000.,  498000.,
        480000.,  488000., 1525000.,  548900.,  725000.,   99000.,
         52000., 2800000.,  499000.,  381000.,  278000.,  690000.,
        260000.,   90001.,  115000., 1599000.,  159000.,   51999.,
        215000.,   35000., 1150000.,  269000.,   60000.,  430000.,
       8500003.,  401919.,  490000.,  424000.,  205000.,  549900.,
        435000.,  189700.,  389700.,  360000.,  295000.,  114990.,
       1065000.,  470000.,   48000.,  188000.,  465000.,  179999.,
       2190000., 2390000., 1075000.,  475000., 1025000.,  615000.,
       1900000., 1490000., 1510000., 1850000.,  790000., 1725000.,
       1225000.,   68000.,  970000., 3100000.,  899000.,   88000.,
         53000.,  568500.,   71000.,  590000.,  795000.,   42000.,
        189000.,  162000.,   35999., 2900000.,   39999.,   50500.,
        510000.,  860000.,  500001.])

In [19]:
df.info()

<class 'pandas.DataFrame'>
Index: 837 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        837 non-null    str
 1   company     837 non-null    str
 2   year        837 non-null    int64
 3   Price       816 non-null    float64
 4   kms_driven  837 non-null    str
 5   fuel_type   837 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 45.8 KB

In [20]:
df.dropna(subset=["Price"],inplace=True)

In [21]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,"45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40 kms,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,"28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,"36,000 kms",Diesel
6,Ford Figo,Ford,2012,175000.0,"41,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000.0,"50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000.0,"30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,300000.0,"1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,260000.0,"27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000.0,"40,000 kms",Diesel

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    int64
 3   Price       816 non-null    float64
 4   kms_driven  816 non-null    str
 5   fuel_type   816 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 44.6 KB

In [23]:
df["fuel_type"].unique()

<StringArray>
['Petrol', 'Diesel', 'LPG']
Length: 3, dtype: str

In [24]:
df.dropna(subset=["fuel_type"],inplace=True)

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    int64
 3   Price       816 non-null    float64
 4   kms_driven  816 non-null    str
 5   fuel_type   816 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 44.6 KB

In [26]:
df["kms_driven"].unique()

<StringArray>
[  '45,000 kms',       '40 kms',   '28,000 kms',   '36,000 kms',
   '41,000 kms',   '25,000 kms',   '24,530 kms',   '60,000 kms',
   '30,000 kms',   '32,000 kms',
 ...
    '1,625 kms',   '33,400 kms',   '60,123 kms', '1,37,495 kms',
   '91,200 kms', '1,46,000 kms', '1,00,800 kms',    '2,100 kms',
    '2,500 kms', '1,32,000 kms']
Length: 248, dtype: str

In [27]:
df["kms_driven"]=df["kms_driven"].str.replace(",","")

In [28]:
df["kms_driven"].unique()

<StringArray>
[ '45000 kms',     '40 kms',  '28000 kms',  '36000 kms',  '41000 kms',
  '25000 kms',  '24530 kms',  '60000 kms',  '30000 kms',  '32000 kms',
 ...
   '1625 kms',  '33400 kms',  '60123 kms', '137495 kms',  '91200 kms',
 '146000 kms', '100800 kms',   '2100 kms',   '2500 kms', '132000 kms']
Length: 248, dtype: str

In [29]:
df["kms_driven"]=df["kms_driven"].str.replace("kms","")

In [30]:
df["kms_driven"].unique()

<StringArray>
[ '45000 ',     '40 ',  '28000 ',  '36000 ',  '41000 ',  '25000 ',  '24530 ',
  '60000 ',  '30000 ',  '32000 ',
 ...
   '1625 ',  '33400 ',  '60123 ', '137495 ',  '91200 ', '146000 ', '100800 ',
   '2100 ',   '2500 ', '132000 ']
Length: 248, dtype: str

In [31]:
df["kms_driven"]=df["kms_driven"].str.strip()

In [32]:
df["kms_driven"].unique()

<StringArray>
[ '45000',     '40',  '28000',  '36000',  '41000',  '25000',  '24530',
  '60000',  '30000',  '32000',
 ...
   '1625',  '33400',  '60123', '137495',  '91200', '146000', '100800',
   '2100',   '2500', '132000']
Length: 248, dtype: str

In [33]:
df["kms_driven"]=pd.to_numeric(df["kms_driven"], errors='coerce')

In [34]:
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    int64
 3   Price       816 non-null    float64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    str
dtypes: float64(1), int64(2), str(3)
memory usage: 44.6 KB

In [35]:
df["name"].unique()

<StringArray>
[  'Hyundai Santro Xing XO eRLX Euro III',
                'Mahindra Jeep CL550 MDI',
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi',
                              'Ford Figo',
                            'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
         'Maruti Suzuki Alto K10 VXi AMT',
            'Skoda Fabia Classic 1.2 MPI',
             'Maruti Suzuki Stingray VXi',
 ...
                     'Mahindra Quanto C4',
              'Maruti Suzuki Swift Dzire',
             'Hyundai i20 Select Variant',
                   'Honda City VX Petrol',
                           'Hyundai Getz',
         'Mercedes Benz C Class 200 K MT',
                            'Skoda Fabia',
             'Maruti Suzuki Ritz VXI ABS',
              'Tata Indica V2 DLE BS III',
                    'Tata Zest XM Diesel']
Length: 463, dtype: str

In [36]:
df.to_csv('cleaned_car_data.csv', index=False)

In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [38]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000,Diesel
6,Ford Figo,Ford,2012,175000.0,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000.0,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000.0,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000.0,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000.0,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000.0,40000,Diesel

In [39]:
df=pd.read_csv('cleaned_car_data.csv')

In [40]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000,Diesel
4,Ford Figo,Ford,2012,175000.0,41000,Diesel
...,...,...,...,...,...,...
811,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000.0,50000,Petrol
812,Tata Indica V2 DLE BS III,Tata,2009,110000.0,30000,Diesel
813,Toyota Corolla Altis,Toyota,2009,300000.0,132000,Petrol
814,Tata Zest XM Diesel,Tata,2018,260000.0,27000,Diesel
815,Mahindra Quanto C8,Mahindra,2013,390000.0,40000,Diesel

In [41]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000,Diesel
4,Ford Figo,Ford,2012,175000.0,41000,Diesel
...,...,...,...,...,...,...
811,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000.0,50000,Petrol
812,Tata Indica V2 DLE BS III,Tata,2009,110000.0,30000,Diesel
813,Toyota Corolla Altis,Toyota,2009,300000.0,132000,Petrol
814,Tata Zest XM Diesel,Tata,2018,260000.0,27000,Diesel
815,Mahindra Quanto C8,Mahindra,2013,390000.0,40000,Diesel

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [43]:
df=pd.read_csv('cleaned_car_data.csv')

In [44]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000,Diesel
4,Ford Figo,Ford,2012,175000.0,41000,Diesel
...,...,...,...,...,...,...
811,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000.0,50000,Petrol
812,Tata Indica V2 DLE BS III,Tata,2009,110000.0,30000,Diesel
813,Toyota Corolla Altis,Toyota,2009,300000.0,132000,Petrol
814,Tata Zest XM Diesel,Tata,2018,260000.0,27000,Diesel
815,Mahindra Quanto C8,Mahindra,2013,390000.0,40000,Diesel

In [45]:
df.duplicated().value_counts()

False    724
True      92
Name: count, dtype: int64

In [47]:
df = df.drop_duplicates()

In [48]:
df.info()

<class 'pandas.DataFrame'>
Index: 724 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        724 non-null    str
 1   company     724 non-null    str
 2   year        724 non-null    int64
 3   Price       724 non-null    float64
 4   kms_driven  724 non-null    int64
 5   fuel_type   724 non-null    str
dtypes: float64(1), int64(2), str(3)
memory usage: 39.6 KB

In [2]:
import numpy as np
import pandas as pd
import sklearn
import streamlit

In [3]:
np.__version__

'2.4.2'

In [4]:
pd.__version__

'3.0.1'

In [5]:
sklearn.__version__

'1.8.0'

In [6]:
streamlit.__version__

'1.56.0'